name: bugtracker
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  alfred: ^0.1.5+1
  dart_dotenv: ^1.0.1
  dart_jsonwebtoken: ^2.4.0
  dbcrypt: ^2.0.0
  dotenv: ^3.0.0
  hive: ^2.0.4

dev_dependencies:
  hive_generator: ^1.1.1
  build_runner: ^2.1.5
  lints: ^1.0.0
